// Design system « Julis » — palette inspirée de la série Daydreaming de Julien Calot.
// Bleus de forêt, lagon, violet de phoenix, jaune d'or et sauge.
export default {
  key: 'julisKey',
  label: 'Julis',
  meta: {
    id: 'julis',
    name: 'Julis',
    description: 'Daydreaming — bleu profond, lagon, phoenix, or & sauge.',
    version: '1.0.0',
    tailwind: true,
  },
  colors: {
    gallery:         { value: '#2B4B74' },
    galleryLight:    { value: '#F2EBD9' },
    galleryMuted:    { value: '#2B4B7455' },
    galleryMuted2:   { value: '#2B4B7477' },
    accent:          { value: '#D9A62E' },
    cream:           { value: '#F2EBD9' },
    surface:         { value: '#FFFDF6' },
    'on-accent':     { value: '#2B4B74' },
    backdrop:        { value: 'rgba(30, 50, 70, 0.66)' },
    'hover-overlay': { value: 'rgba(255, 255, 255, 0.3)' },
    'subtle-overlay':{ value: 'rgba(255, 255, 255, 0.12)' },
    'faint-overlay': { value: 'rgba(255, 255, 255, 0.06)' },
    'hero-vignette': { value: 'rgba(43, 75, 116, 0.18)' },
    // Palette Daydreaming (Julien Calot) — le cheval, la forêt, le lagon, la sauge, le phoenix
    nuit:        { value: '#22354E' },
    foret:       { value: '#3E7B9E' },
    ciel:        { value: '#46A7D8' },
    cielPale:    { value: '#A7D7E8' },
    lagon:       { value: '#257A78' },
    lagonClair:  { value: '#6FBFB8' },
    sauge:       { value: '#5F8C77' },
    saugeClair:  { value: '#A9C2A6' },
    phoenix:     { value: '#665B8F' },
    phoenixClair:{ value: '#A89BC4' },
    or:          { value: '#D9A62E' },
    orClair:     { value: '#EFD896' },
    craie:       { value: '#F2EBD9' },
  },
  font: {
    display: {
      families: ['Fraunces'],
      weights: '400;500;600',
      fallbacks: ['Georgia', 'serif'],
    },
    body: {
      families: ['Bricolage Grotesque'],
      weights: '400;600',
      fallbacks: ['system-ui', 'sans-serif'],
    },
  },
  typography: {
    sizes: {
      hero:      { value: '2.75rem' },
      display:   { value: '2.25rem' },
      featured:  { value: '1.875rem' },
      lead:      { value: '1.2rem' },
      cardTitle: { value: '1.15rem' },
      base:      { value: '1rem' },
      small:     { value: '0.875rem' },
      xsmall:    { value: '0.75rem' },
      micro:     { value: '0.65rem' },
    },
    tracking: {
      tight: { value: '0.02em' },
      label: { value: '0.06em' },
      wide:  { value: '0.12em' },
      wider: { value: '0.2em' },
    },
  },
  radius: {
    cards:   { value: '14px' },
    buttons: { value: '9999px' },
    fields:  { value: '10px' },
    md:      { value: '10px' },
    sm:      { value: '4px' },
    image:   { value: '4px' },
    photo:   { value: '8px' },
  },
  shadow: {
    card: { value: '0 10px 28px rgba(43, 75, 116, 0.28)' },
    lift: { value: '0 8px 20px rgba(43, 75, 116, 0.24)' },
    photo: { value: '0 12px 30px rgba(46, 97, 136, 0.22)' },
    glow: { value: '0 0 0 3px rgba(217, 166, 46, 0.35)' },
  },
  spacing: {
    containerMaxWidth: { value: '74rem' },
  },
  // Affichage complet de la grille (GridView) — fidèle à juliencalot.com (5 col., gaps fluides, aspect naturel)
  grid: {
    gutter: { value: 'max(20px, 1.1111vw)' },
    columns: { value: '1fr 1fr 1fr 1fr 1fr' },
    columnsTablet: { value: '1fr 1fr 1fr 1fr' },
    columnsMobile: { value: '1fr 1fr' },
    columnGap: { value: '9.25vw' },
    rowGap: { value: '11vw' },
    gapMobile: { value: '50px' },
    gapSmall: { value: '20px' },
    padding: { value: 'max(40px, 2.2222vw) max(20px, 1.1111vw)' },
    cellBg: { value: 'transparent' },
    cellPadding: { value: '0px' },
    cellRadius: { value: '0px' },
    cellBorder: { value: 'transparent' },
    cellBorderWidth: { value: '0px' },
    cellDisplay: { value: 'block' },
    mediaAspect: { value: 'auto' },
    mediaHeight: { value: 'auto' },
    mediaFit: { value: 'contain' },
    glbAspect: { value: '1 / 1' },
    titleGap: { value: 'max(8px, 0.4444vw)' },
    titleSize: { value: 'max(8px, 0.4444vw)' },
    titleWeight: { value: '900' },
    titleColor: { value: '#2B4B74' },
    titleFamily: { value: "'Bricolage Grotesque', system-ui, sans-serif" },
    titleSpacing: { value: '0.02em' },
    titleAlign: { value: 'center' },
    titleDisplay: { value: 'block' },
    titleHidden: { value: 'translate3d(0, -200%, 0)' },
    titleVisible: { value: 'translate3d(0, 0, 0)' },
    revealDuration: { value: '0.5s' },
    hoverLift: { value: 'none' },
    hoverShadow: { value: 'none' },
    cardBg: { value: '#F2EBD9' },
    cardColor: { value: '#2B4B74' },
    labelDisplay: { value: 'block' },
  },
  // Affichage complet de la liste (ListView) — photo 4/12, texte série à gauche, titre+artiste+témoin à droite
  list: {
    direction: { value: 'row' },
    justify: { value: 'space-between' },
    rowGap: { value: 'max(60px, 3.3333vw)' },
    boxPadding: { value: 'max(20px, 1.1111vw)' },
    seriesDisplay: { value: 'block' },
    seriesSize: { value: 'max(18px, 1vw)' },
    seriesWeight: { value: '900' },
    seriesColor: { value: '#2B4B74' },
    seriesSpacing: { value: '0.02em' },
    seriesFamily: { value: "'Bricolage Grotesque', system-ui, sans-serif" },
    stagePosition: { value: 'absolute' },
    stageLeft: { value: '50%' },
    stageTop: { value: '50%' },
    stageTransform: { value: 'translate(-50%, -50%)' },
    stageGap: { value: '1.5rem' },
    photoWidth: { value: 'calc((100% - 11 * var(--grid-gutter)) / 12 * 4 + var(--grid-gutter) * 3)' },
    photoPadding: { value: '0px' },
    photoBg: { value: 'transparent' },
    photoRadius: { value: '0px' },
    photoShadow: { value: 'none' },
    mediaWidth: { value: '100%' },
    mediaMaxW: { value: 'none' },
    mediaMaxH: { value: 'calc(100vh - 12rem)' },
    mediaAspect: { value: 'auto' },
    mediaFit: { value: 'contain' },
    glbAspect: { value: '1 / 1' },
    infoWidth: { value: 'calc((100% - 11 * var(--grid-gutter)) / 12 * 4 + var(--grid-gutter) * 3)' },
    infoAlign: { value: 'right' },
    infoMargin: { value: '0px' },
    infoOpacity: { value: '1' },
    titleSize: { value: 'max(18px, 1vw)' },
    titleWeight: { value: '900' },
    titleColor: { value: '#2B4B74' },
    titleSpacing: { value: '0.02em' },
    titleFamily: { value: "'Fraunces', Georgia, serif" },
    metaSize: { value: 'max(10px, 0.6vw)' },
    metaColor: { value: '#5C7291' },
    metaOpacity: { value: '0.85' },
    navSize: { value: 'max(24px, 2rem)' },
    navColor: { value: '#2B4B74' },
    navHover: { value: '#D9A62E' },
    counterSize: { value: 'max(8px, 0.4444vw)' },
    counterColor: { value: '#5C7291' },
    counterSpacing: { value: '0.06em' },
    cardBg: { value: '#F2EBD9' },
    cardColor: { value: '#2B4B74' },
    cardRadius: { value: '6px' },
  },
  motion: {
    marqueeDuration:   { value: '16s' },
    blinkDuration:     { value: '1.1s' },
    transitionDuration: { value: '280ms' },
    slowTransition:     { value: '380ms' },
    // Courbe d'aisance « epic » du site juliencalot.com
    easeInOutEpic: { value: 'cubic-bezier(0.75, 0.25, 0.25, 0.75)' },
  },
  animations: {
    marquee:     { timing: 'linear', iteration: 'infinite' },
    cursorBlink: { timing: 'ease-in-out', iteration: 'infinite' },
    cardFlip:    { duration: '0.5s' },
  },
}