// Design system « Matrice » — le design actuel du projet.
export default {
  key: 'matriceKey',
  label: 'Matrice',
  meta: {
    id: 'matrice',
    name: 'Matrice',
    description: 'Vert olive & beige, typographies Kalnia / Almendra Sans.',
    version: '1.0.0',
    tailwind: true,
  },
  colors: {
    gallery:         { value: '#313927' },
    galleryLight:    { value: '#E4D3B5' },
    galleryMuted:    { value: '#31392755' },
    galleryMuted2:   { value: '#31392777' },
    accent:          { value: '#313927' },
    cream:           { value: '#E4D3B5' },
    surface:         { value: '#fffdf7' },
    'on-accent':     { value: '#000000' },
    backdrop:        { value: 'rgba(0, 0, 0, 0.6)' },
    'hover-overlay': { value: 'rgba(255, 255, 255, 0.3)' },
    'subtle-overlay':{ value: 'rgba(255, 255, 255, 0.1)' },
    'faint-overlay': { value: 'rgba(255, 255, 255, 0.05)' },
    'hero-vignette': { value: 'rgba(49, 57, 39, 0.18)' },
    // Palette étendue — même schéma que julis, valeurs propres à Matrice
    nuit:        { value: '#2B2E24' },
    foret:       { value: '#4A6741' },
    ciel:        { value: '#6E8B74' },
    cielPale:    { value: '#A3B8A0' },
    lagon:       { value: '#3A5F5A' },
    lagonClair:  { value: '#7B9E94' },
    sauge:       { value: '#6B7F5E' },
    saugeClair:  { value: '#A3B397' },
    phoenix:     { value: '#7A6A52' },
    phoenixClair:{ value: '#B8A88A' },
    or:          { value: '#C9A83E' },
    orClair:     { value: '#E8D48F' },
    craie:       { value: '#E4D3B5' },
  },
  font: {
    display: {
      families: ['Kalnia'],
      weights: '400;500;600',
      fallbacks: ['Georgia', 'serif'],
    },
    body: {
      families: ['Almendra Sans'],
      weights: '400;700',
      fallbacks: ['system-ui', 'sans-serif'],
    },
  },
  typography: {
    sizes: {
      hero:      { value: '3rem' },
      display:   { value: '2.5rem' },
      featured:  { value: '2rem' },
      lead:      { value: '1.25rem' },
      cardTitle: { value: '1.2rem' },
      base:      { value: '1rem' },
      small:     { value: '0.875rem' },
      xsmall:    { value: '0.75rem' },
      micro:     { value: '0.65rem' },
    },
    tracking: {
      tight: { value: '0.025em' },
      label: { value: '0.05em' },
      wide:  { value: '0.1em' },
      wider: { value: '0.18em' },
    },
  },
  radius: {
    cards:   { value: '18px' },
    buttons: { value: '9999px' },
    fields:  { value: '10px' },
    md:      { value: '12px' },
    sm:      { value: '2px' },
    image:   { value: '2px' },
    photo:   { value: '4px' },
  },
  shadow: {
    card:  { value: '0 10px 30px rgba(0, 0, 0, 0.25)' },
    lift:  { value: '0 8px 20px rgba(0, 0, 0, 0.25)' },
    photo: { value: '0 12px 30px rgba(49, 57, 39, 0.22)' },
    glow:  { value: '0 0 0 3px rgba(49, 57, 39, 0.25)' },
  },
  spacing: {
    containerMaxWidth: { value: '72rem' },
  },
  // Grille (GridView) — même schéma de tokens que julis, valeurs propres à Matrice
  grid: {
    gutter: { value: '0.8rem' },
    columns: { value: 'repeat(3, 1fr)' },
    columnsTablet: { value: 'repeat(3, 1fr)' },
    columnsMobile: { value: 'repeat(3, 1fr)' },
    columnGap: { value: '0.8rem' },
    rowGap: { value: '0.8rem' },
    gapMobile: { value: '0.8rem' },
    gapSmall: { value: '0.8rem' },
    padding: { value: '4rem 5rem 5rem' },
    paddingX: { value: '5rem' },
    columnsCount: { value: '3' },
    columnWidth: {
      value: 'calc((100vw - 2 * var(--grid-padding-x, 5rem) - (var(--grid-columns-count, 3) - 1) * var(--grid-column-gap, 0.8rem)) / var(--grid-columns-count, 3))',
    },
    rowWidth: { value: 'var(--grid-column-width)' },
    cellBg: { value: '#fffdf7' },
    cellPadding: { value: '0.4rem' },
    cellRadius: { value: '0px' },
    cellBorder: { value: 'transparent' },
    cellBorderWidth: { value: '0px' },
    cellDisplay: { value: 'flex' },
    mediaAspect: { value: '1' },
    mediaHeight: { value: '100%' },
    mediaFit: { value: 'cover' },
    glbAspect: { value: '1' },
    titleGap: { value: '0.5rem' },
    titleSize: { value: '0.8rem' },
    titleWeight: { value: '600' },
    titleColor: { value: '#313927' },
    titleFamily: { value: "'Almendra Sans', system-ui, sans-serif" },
    titleSpacing: { value: '0.02em' },
    titleAlign: { value: 'center' },
    titleDisplay: { value: 'block' },
    titleHidden: { value: 'none' },
    titleVisible: { value: 'none' },
    revealDuration: { value: '0.4s' },
    hoverLift: { value: 'translateY(-4px)' },
    hoverShadow: { value: '0 8px 20px rgba(0, 0, 0, 0.25)' },
    cardBg: { value: '#fffdf7' },
    cardColor: { value: '#313927' },
    labelDisplay: { value: 'none' },
  },
  // Liste (ListView) — même schéma de tokens que julis, colonne centrée façon Matrice
  list: {
    direction: { value: 'column' },
    justify: { value: 'center' },
    rowGap: { value: '1.5rem' },
    boxPadding: { value: '0px' },
    seriesDisplay: { value: 'none' },
    seriesSize: { value: 'max(18px, 1vw)' },
    seriesWeight: { value: '700' },
    seriesColor: { value: '#313927' },
    seriesSpacing: { value: '0.02em' },
    seriesFamily: { value: "'Kalnia', Georgia, serif" },
    stagePosition: { value: 'static' },
    stageLeft: { value: 'auto' },
    stageTop: { value: 'auto' },
    stageTransform: { value: 'none' },
    stageGap: { value: '1.5rem' },
    photoWidth: { value: 'var(--grid-column-width)' },
    photoHeight: { value: 'var(--grid-row-width)' },
    photoPadding: { value: '0.4rem' },
    photoBg: { value: '#fffdf7' },
    photoRadius: { value: '0px' },
    photoShadow: { value: 'none' },
    photoAspect: { value: '1' },
    mediaWidth: { value: '100%' },
    mediaMaxW: { value: 'none' },
    mediaMaxH: { value: '100%' },
    mediaAspect: { value: '1' },
    mediaFit: { value: 'cover' },
    glbAspect: { value: '1' },
    infoWidth: { value: 'auto' },
    infoAlign: { value: 'center' },
    infoMargin: { value: '0.8rem' },
    infoOpacity: { value: '1' },
    titleSize: { value: 'var(--type-cardTitle)' },
    titleWeight: { value: '600' },
    titleColor: { value: '#313927' },
    titleSpacing: { value: '0.02em' },
    titleFamily: { value: "'Kalnia', Georgia, serif" },
    metaSize: { value: 'var(--type-base)' },
    metaColor: { value: '#31392777' },
    metaOpacity: { value: '0.85' },
    navSize: { value: '32px' },
    navColor: { value: '#313927' },
    navHover: { value: '#31392777' },
    counterSize: { value: 'var(--type-small)' },
    counterColor: { value: '#313927' },
    counterSpacing: { value: '0.18em' },
    cardBg: { value: '#fffdf7' },
    cardColor: { value: '#313927' },
    cardRadius: { value: '0px' },
  },
  motion: {
    marqueeDuration:   { value: '18s' },
    blinkDuration:     { value: '1.2s' },
    transitionDuration: { value: '300ms' },
    slowTransition:     { value: '400ms' },
    easeInOutEpic: { value: 'cubic-bezier(0.6, 0.1, 0.15, 1)' },
  },
  animations: {
    marquee:     { timing: 'linear', iteration: 'infinite' },
    cursorBlink: { timing: 'ease-in-out', iteration: 'infinite' },
    cardFlip:    { duration: '0.6s' },
  },
}